server:
  port: 8080
  context-path: /feifei
spring:
    datasource:
        url: jdbc:mysql://140.207.81.233:3396/wangtao_self?useUnicode=true&characterEncoding=utf8
        username: root
        password: huidong123123.-
        driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql